version: '3'
services:
  client:
    image: docker.io/kyoheiudev/carbon-client:0.2.0
    container_name: carbon-client
    volumes:
      - '/path/to/data:/carbon-client/data:rw'
    environment:
      - CARBON_GIT_SERVER=carbon-server
    ports:
      - 3000:3000
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'
  # If you do not want the git feature, omit `server` entirely!
  server:
    image: docker.io/kyoheiudev/carbon-server:0.2.0
    container_name: carbon-server
    # UID and GID that created Git repository.
    user: '1000:1000'
    volumes:
      - './data:/carbon-server/data:rw'
      - '/etc/passwd:/etc/passwd:ro'
      - '/etc/group:/etc/group:ro'
    environment:
      # default to 'carbon'
      - CARBON_GIT_USER="carbon"
      # default to 'git@example.com'
      - CARBON_GIT_EMAIL="git@example.com"
      - CARBON_DATA_PATH=data
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'
