version: '3'
services:
  carbon:
    image: docker.io/kyoheiudev/carbon:0.3.1
    container_name: carbon
    volumes:
      - '/path/to/data:/carbon-client/data:rw'
    environment:
      # If you do not want the git feature, omit this!
      - CARBON_GIT_SERVER=carbon-git
    ports:
      - 3000:3000
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'
  # If you don't want the git feature, omit `carbon-git` entirely!
  carbon-git:
    image: docker.io/kyoheiudev/carbon-git:1.0.0
    container_name: carbon-git
    # UID and GID that created Git repository.
    user: '1000:1000'
    volumes:
      - './data:/carbon-git/data:rw'
      - '/etc/passwd:/etc/passwd:ro'
      - '/etc/group:/etc/group:ro'
    environment:
      # default to 'carbon'
      - CARBON_GIT_USER="carbon"
      # default to 'git@example.com'
      - CARBON_GIT_EMAIL="git@example.com"
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'
